# Generated by Django 2.2.3 on 2020-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebay', '0003_auto_20200324_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='starred',
            field=models.ManyToManyField(related_name='starred', to='treebay.Plant'),
        ),
    ]
