# Generated by Django 2.2.3 on 2020-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebay', '0004_auto_20200324_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
